In [1]:
import numpy as np

In [3]:
A = np.array([0,1,2,3,4,5,6,7,8,9])

In [5]:
np.random.shuffle(A)

In [6]:
A 

array([4, 2, 7, 3, 8, 5, 6, 0, 1, 9])

In [7]:
for i in A:
    print(A[i])

8
7
0
3
1
5
6
4
2
9


In [12]:
B = np.arange(0,10)
print(B)
np.random.shuffle(B)
print(B)

[0 1 2 3 4 5 6 7 8 9]
[4 3 7 1 2 5 6 8 9 0]
